.MODEL SMALL
.DATA
NO_VOW_MESSAGE DB 'THERE IS NO VOWEL IN YOUR STRING$'
VOW_MESSAGE DB 'THERE ARE VOWELS IN YOUR STRING$'
NUM_VOW DB 'THE NUMBER OF VOWELS: $'

.CODE
MAIN PROC
    MOV BX,0H
    MOV CX,100H
    FIND_VOWEL:
    CALL TAKE_INPUT 
    CMP AL,0DH
    JE DISPLAY_OUTPUT
    CMP AL,'A'
    JE VOWEL
    CMP AL,'E'
    JE VOWEL
    CMP AL,'I'
    JE VOWEL
    CMP AL,'O'
    JE VOWEL
    CMP AL,'U'
    JE VOWEL
    JMP FIND_VOWEL

    VOWEL:
    INC BL
    JMP FIND_VOWEL
    DISPLAY_OUTPUT:
    CALL NEW_LINE
    CMP BL,0
    JE NO_VOWEL_MESSAGE
    JMP VOWEL_MESSAGE
    HLT 

    NO_VOWEL_MESSAGE:
    MOV AX,@DATA
    MOV DS,AX

    MOV AH,09H
    LEA DX,NO_VOW_MESSAGE
    INT 21H
    HLT

    VOWEL_MESSAGE:
    MOV AX,@DATA
    MOV DS,AX

    MOV AH,09H
    LEA DX,VOW_MESSAGE
    INT 21H
    CALL NEW_LINE
    MOV AH,09H
    LEA DX,NUM_VOW
    INT 21H


    CMP BL,10
    JB NOT_MORE_TEN 
    MOV AX,0
    MOV AL,BL
    MOV BL,10
    DIV BL
    MOV BL,AL
    MOV BH,AH
    ADD BL,48D
    ADD BH,48D
    MOV DL,BL
    MOV AH,02H
    INT 21H
    MOV DL,BH
    MOV AH,02H
    INT 21H

    HLT

    NOT_MORE_TEN:
    ADD BL,48D
    MOV DL,BL
    MOV AH,02H
    INT 21H
    HLT

    
    MAIN ENDP
TAKE_INPUT PROC
    MOV AH,01H
    INT 21H
    RET
    TAKE_INPUT ENDP
NEW_LINE PROC
    MOV AH,2
    MOV DL,0AH
    INT 21H
    MOV AH,2
    MOV DL,0DH
    INT 21H
    RET
    NEW_LINE ENDP