.MODEL SMALL 
.STACK 
.DATA 
.CODE 

MAIN PROC   
    
    MOV AX ,@DATA 
    MOV DS, AX     ; LOAD DATA TO THE DATA SEGMENT REGISTER 
    
    MOV AH , 1   ; INPUT FUNCTION FROM I/O DEVICE 
    INT 21H
    
    MOV CL ,AL ; MOV DATA TO CL REGISTER FROM AL  
     
    MOV AH , 2  ; NEW LINE FUNCTION
    MOV DL, 0AH
    INT 21H 
    
    MOV AH , 2    ; CARSOR RETURN FUNCTION
    MOV DL , 0DH 
    INT 21H 
    
    MOV DL , CL  ; LOAD DATA TO THE DL REGISTER FROM CL 
    
    MOV AH , 2  ; CHARECTER SHOW FUNCTION  
    INT 21H    
    
    MAIN ENDP 
END MAIN 
    